### ISSUE TITLE
The links of few social media platform are not working

### ISSUE THREAD

**Issue by Parthmandale** [gdscbvppune/gdscbvppune.github.io#11]
## Description:
The links on the icon of GitHub and Instagram are not working, this may not be a good thing from a visitor's perspective.

## Solution:
The correct links are needed to be added in place of the links which are outdated.

**Comment by Parthmandale** [comment]
@asmitbm you can assign this to me.

**Comment by asmitbm** [comment]
> @asmitbm you can assign this to me.

Sure go ahead

**Comment by Parthmandale** [comment]
@asmitbm issue no. #11 has been solved!
